name: Download custom actions
description: Download custom actions from s3
inputs:
  action-name:
    description: The action name to be downloaded
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Download from S3
      env:
          S3_BUCKET_NAME: ${{ secrets.CUSTOM_ACTIONS_S3_BUCKET }}
          ACTION_NAME: ${{ inputs.action-name }}
      run: aws s3 cp s3://$S3_BUCKET_NAME/$ACTION_NAME.zip ./.github/actions
      shell: bash
    - name: Unzip the composite actions file
      run: |
        unzip -d ./.github/actions/$ACTION_NAME ./.github/actions/$ACTION_NAME.zip
        rm ./.github/actions/$ACTION_NAME.zip
        ls ./.github/actions/
      shell: bash